# Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a[0])
print(a[1])

1
2


In [3]:
for i in a:
    print(a)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [4]:
sum=a[1]+a[3]
print(f"Sum of {a[1]} and {a[3]} is {sum}")

Sum of 2 and 4 is 6


In [5]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[0,1])
print(b[1,1])
print(b[1,-1])
print(b[0,-2])

2
7
10
4


In [6]:
a= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a[0, 1, 2])
print(a[1, 1, -2])

6
11
